name: Run mypy, pylint and pytest

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy pylint pytest pydantic requests requests-mock

      - name: Run mypy
        run: mypy py3xui

      - name: Run pylint
        run: pylint py3xui

      - name: Run pytest
        run: pytest