on:
  issues:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add comment to new issue
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          context.github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ` 
                Thank you for opening an issue!
                Please, first check our [FAQ](https://github.com/iwatkot/py3xui/discussions/categories/faq) section in discussions to see if your question has already been answered.
                You can also use Discussion if you have any questions or suggestions, while the Issues section is for bug reports and feature requests.

                If you want to proceed with the issue, please provide the following information:
                - Description of the issue
                - Expected behavior
                - Actual behavior
            `
          });