name: Issue FAQ
on:
  issues:
    types:
      - opened
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Thank you for opening an issue!<br>
            Please, first check our [FAQ](https://github.com/iwatkot/py3xui/discussions/categories/faq) section in discussions to see if your question has already been answered.<br>
            You can also use Discussion if you have any questions or suggestions, while the Issues section is for bug reports and feature requests.<br>

            If you want to proceed with the issue, please provide the following information:<br>
            - Description of the issue<br>
            - Expected behavior<br>
            - Actual behavior<br>
            - Steps to reproduce the issue<br>
            - Python version<br>
            - OS<br>
            - py3xui version<br>
            - 3x-UI version<br>
            - Code snippet or a minimal example to reproduce the issue (if applicable)<br>
            - JSON representation of the request to the API (if applicable)<br>


            Thank you!